name: Main CI/CD Workflow
on:
  push:
    branches:
      - main
      - dev
      - uat
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [main, dev, uat, qa]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          distribution: 'us-east-1'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up environment-specific workflow
        uses: actions/github-script@v4
        with:
          script: |
            const environment = '${{ matrix.environment }}';
            switch (environment) {
            
              case 'dev':
                github.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'deploy-dev.yml'
                });
                break;

              default:
                throw new Error(`Unknown environment: ${environment}`);
            }
